pygments: true
permalink: /:year/:month/:title.html
redirect_permalinks:
  - none
  - date
  - pretty
  - :title/
  - :title.html
  - /:year/:month/:day/:title.html
  - /:year/:month/:title.html

# server: true
# auto: true
paginate: 10
